#### NUMPY SELECTION, INDEXING AND OPERATIONS

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[7]

np.int64(7)

In [5]:
arr[0:4]

array([0, 1, 2, 3])

In [6]:
arr[:4]

array([0, 1, 2, 3])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

***BROADCASTING AND COPYING(ONLY IN NUMPY NOT IN LIST)***

In [9]:
arr[0:5] = 20 #assign same value to multiple rows and columns if needed

In [10]:
arr

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9, 10])

In [44]:
arr=np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
slice_of_arr = arr[0:5]

In [47]:
slice_of_arr[:] = 100 # changes main array values also

In [48]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [49]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
arr=np.arange(0,9)

In [51]:
arr_copy = arr.copy() # to avoid changing the main array use copy in numpy

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
arr_copy[:] = 100

In [55]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100])

In [56]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

**2D array- indexing and slicing**

In [57]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [58]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr_2d.shape

(3, 3)

In [60]:
arr_2d[1][1] #method 1 #first bracket row, second column

np.int64(5)

In [61]:
arr_2d[1,1] #method 2

np.int64(5)

In [64]:
arr_2d[:2,1:] # first parameter rows, second column (all rows till 2, 1 column till end), should be comma separated

array([[2, 3],
       [5, 6]])

**Conditional Selection**

In [65]:
arr = np.arange(0,10)

In [66]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [68]:
bool_arr = arr>4

In [69]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [70]:
arr[bool_arr] # condition checked for True

array([5, 6, 7, 8, 9])

In [71]:
arr[arr>4]

array([5, 6, 7, 8, 9])

#### NUMPY OPERATIONS

In [72]:
arr = np.arange(0,10)

In [73]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr +5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [75]:
arr -5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [76]:
arr* 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [77]:
arr +arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [79]:
arr / arr # 0/0 gives nan and not raising error,but only warning

C:\Users\KANCHANA SRIRAM\AppData\Local\Temp\ipykernel_13108\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [80]:
1/arr # num/0 gives infinity and not raising error, but only warning

C:\Users\KANCHANA SRIRAM\AppData\Local\Temp\ipykernel_13108\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [81]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [82]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [83]:
np.log(arr)

C:\Users\KANCHANA SRIRAM\AppData\Local\Temp\ipykernel_13108\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [84]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
#np.sum(arr) 
sum(arr)

In [86]:
np.mean(arr) #mean(arr)

np.float64(4.5)

In [87]:
np.var(arr)# var(arr)

np.float64(8.25)

In [93]:
np.std(arr)
#arr.std()

np.float64(2.8722813232690143)

In [94]:
arr_2d = np.arange(0,25).reshape(5,5)

In [95]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [96]:
arr_2d.sum()

np.int64(300)

In [97]:
arr_2d.sum(axis=0) # sum accross rows

array([50, 55, 60, 65, 70])

In [98]:
arr_2d.sum(axis=1) #sum accross columns

array([ 10,  35,  60,  85, 110])