#### Numpy Arrays

**Creating Numpy array different methods**

**Method 1 using np.array(list)**

In [3]:
!pip install numpy

In [4]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_array = np.array(my_list)

In [4]:
my_array

array([1, 2, 3])

In [5]:
my_list

[1, 2, 3]

In [8]:
print(type(my_list))
print(type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_n_array = np.array(my_matrix)

In [12]:
print(my_matrix)
print(type(my_matrix))
print(my_n_array)
print(type(my_n_array))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


**Method 2 using np.arange(start,stop,step), np.zeros(shape), np.ones(shape)**

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [16]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

**numpy array default values are float**

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [20]:
np.ones((2,2,2,2))

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

**Method 3 using linspace(start,stop,count) and eye(number)**

In [8]:
np.linspace(1,5,3) #linear space between start and end number, till the count of numbers met

array([1., 3., 5.])

In [6]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [10]:
len(np.linspace(0,100,101))  # length will match the count provided

101

In [11]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Method 4 using random distribution**

In [12]:
np.random.rand(5) #uniform distribution on number between 0 and 1, for the provided count

array([0.60902409, 0.21585782, 0.02085219, 0.5031018 , 0.33234259])

In [13]:
np.random.rand(4,2) #n dimensional uniform distribution

array([[0.41796023, 0.08580973],
       [0.40706141, 0.05731968],
       [0.84181462, 0.10752153],
       [0.30624503, 0.94529488]])

In [14]:
np.random.randn(5) # standard uniform distribution allow negative numbers, mean 0 and variance 1

array([-0.34381014, -1.37161099, -0.49401201, -0.02961208,  0.85384942])

In [15]:
np.random.randn(3,3)

array([[-0.07322521, -0.13056405, -1.38399511],
       [ 0.01937936, -0.17131305, -0.13584926],
       [ 0.13631677,  0.16478158,  1.1383907 ]])

In [16]:
np.random.randint(10,20,4) # integers between start and stop, for the shape of array

array([10, 13, 11, 18], dtype=int32)

In [17]:
np.random.randint(10,30,(3,3))

array([[23, 26, 27],
       [23, 18, 16],
       [29, 25, 20]], dtype=int32)

**with seed same random numbers everytime, when used in same cell**
**without seed rand provides, different array**
**any number can be used in seed, not only 100(that's example)**

In [18]:
np.random.seed(100)
np.random.rand(3)

array([0.54340494, 0.27836939, 0.42451759])

In [19]:
np.random.seed(100)
np.random.rand(3)

array([0.54340494, 0.27836939, 0.42451759])

In [20]:
np.random.rand(3)

array([0.84477613, 0.00471886, 0.12156912])

**Method 5 shape and reshape**

In [26]:
arr1=np.arange(0,25)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [32]:
arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr1.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [36]:
ranarr = np.random.randint(0,50,10)

In [37]:
ranarr

array([ 2, 34, 14, 34, 49, 48, 24, 15, 36, 43], dtype=int32)

In [38]:
ranarr.max() #provides largest number 

np.int32(49)

In [39]:
ranarr.argmax() #provides index of the largest number

np.int64(4)

In [40]:
ranarr.min()

np.int32(2)

In [41]:
ranarr.argmin()

np.int64(0)

In [42]:
ranarr.dtype

dtype('int32')

In [43]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr1.shape #output is a tuple is because, one set of list (depicts 1 row 25 columns)

(25,)

In [51]:
arr1.reshape(25,1) # 25 separate rows

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [52]:
arr1.reshape(1,25) # 25 values in 1 row

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [50]:
arr1 = arr1.reshape(5,5)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [48]:
arr1.shape

(5, 5)